### ISSUE TITLE
Sandbox-related issue at attempt to install capitaine-xcursors

### ISSUE THREAD

**Issue by jorgicio** [beatussum/beatussum-overlay#3]
Hi!

I'm trying to install your package of capitaine-xcursors and there are lots of sandbox-related messages you can view and this paste:

http://pastebin.calculate-linux.org/en/show/139717

Thanks!

**Comment by beatussum** [comment]
I don't manage to reproduce this issue… Could you give the output of `emerge --info media-gfx/inkscape sys-apps/dbus x11-apps/xcursorgen`?

**Comment by jorgicio** [comment]
Sure, it is:

http://pastebin.calculate-linux.org/en/show/139790

**Comment by beatussum** [comment]
In the end, even with the same **EMERGE_DEFAULT_OPTS**, **FEATURES** and **USE**, I don't manage to reproduce this issue but I think it's come from `dbus-run-session`: I added it (in the patch called `files/capitaine-xcursors-4-fix-inkscape-cli.patch`) to avoid some D-Bus warnings. I think, in the end, this may cause some side effects hence the sandbox-related messages you get.  
You can maybe fix that by using a user patch:

```
sudo curl --create-dirs -o /etc/portage/patches/x11-themes/capitaine-xcursors/fix-inkscape-command-line.patch "https://dpaste.com/6X7QMY2P8.txt"
```

Hoping that this will help you :confused:

**Comment by jorgicio** [comment]
Yes, the patch you provided fixed this issue. Thank you.

I don't know if is this related with using elogind. But anyways, it worked.
