### ISSUE TITLE
move the good stuff to guru

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [beatussum/beatussum-overlay#6]
[guru](https://wiki.gentoo.org/wiki/Project:GURU)  is an official and collaborative overlay. I already taken some ebuild of yours and put there, what about moving the rest?

**Comment by beatussum** [comment]
I've already heard about the existence of the GURU project; yet, I prefer to have my own overlay where I can feel more free of its management. I'm sorry but I'm not interested in this idea; however, you can add yourself the ebuilds which you want to maintain into the GURU repository.
